services:

  mysql:
    image: mysql:8.4

    container_name: ocorrencias-mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - ocorrencias-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s


  backend:
    image: tunerw/ocorrencias-backend:1.0.1

    container_name: ocorrencias-backend

    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - uploads_data:/app/upload

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ocorrencias-network


  frontend:
    image: tunerw/ocorrencias-frontend:1.0.0

    container_name: ocorrencias-frontend

    ports:
      - "8082:80"

    depends_on:
      backend:
        condition: service_started

    networks:
      - ocorrencias-network


volumes:

  mysql_data:

  uploads_data:


networks:

  ocorrencias-network: